/**
 * Common cannabis terpenes for autocomplete suggestions.
 * Sorted alphabetically for consistent display.
 */
export const TERPENE_LIST: string[] = [
  'Alpha-Bisabolol',
  'Alpha-Cedrene',
  'Alpha-Phellandrene',
  'Alpha-Pinene',
  'Alpha-Terpineol',
  'Alpha-Thujone',
  'Beta-Caryophyllene',
  'Beta-Cedrene',
  'Beta-Myrcene',
  'Beta-Phellandrene',
  'Beta-Pinene',
  'Beta-Terpineol',
  'Bisabolol',
  'Borneol',
  'Camphene',
  'Camphor',
  'Carvacrol',
  'Carvone',
  'Caryophyllene',
  'Caryophyllene Oxide',
  'Cedrene',
  'Cedrol',
  'Citral',
  'Citronellol',
  'Cymene',
  'Delta-3-Carene',
  'Eucalyptol',
  'Eugenol',
  'Farnesene',
  'Farnesol',
  'Fenchol',
  'Fenchone',
  'Geraniol',
  'Geranyl Acetate',
  'Guaiol',
  'Humulene',
  'Isobornyl Acetate',
  'Isoborneol',
  'Isopulegol',
  'Limonene',
  'Linalool',
  'Menthol',
  'Menthone',
  'Myrcene',
  'Nerol',
  'Nerolidol',
  'Nootkatone',
  'Ocimene',
  'Octyl Acetate',
  'Phytane',
  'Phytol',
  'Piperitone',
  'Pulegone',
  '(R)-Endo-(+)-Fenchyl Alcohol',
  'Sabinene',
  'Safranal',
  'Squalene',
  'Terpinen-4-ol',
  'Terpineol',
  'Terpinolene',
  'Thujone',
  'Thymol',
  'Trans-Caryophyllene',
  'Valencene',
  'Verbenone',
  'd-Valerolactam (2-piperidone)',
];
