/**
 * Common cannabis terpenes for autocomplete suggestions.
 * Sorted alphabetically for consistent display.
 * Covers standard + extended Canadian LP CoA panels (~96 terpenes).
 */
export const TERPENE_LIST: string[] = [
  'Alpha-Bergamotene',
  'Alpha-Bisabolene',
  'Alpha-Bisabolol',
  'Alpha-Cedrene',
  'Alpha-Cubebene',
  'Alpha-Gurjunene',
  'Alpha-Humulene',
  'Alpha-Ocimene',
  'Alpha-Phellandrene',
  'Alpha-Pinene',
  'Alpha-Selinene',
  'Alpha-Terpinene',
  'Alpha-Terpineol',
  'Alpha-Thujone',
  'Aromadendrene',
  'Beta-Bisabolene',
  'Beta-Caryophyllene',
  'Beta-Cedrene',
  'Beta-Elemene',
  'Beta-Eudesmol',
  'Beta-Myrcene',
  'Beta-Ocimene',
  'Beta-Phellandrene',
  'Beta-Pinene',
  'Beta-Selinene',
  'Beta-Terpineol',
  'Bisabolol',
  'Borneol',
  'Bulnesol',
  'Camphene',
  'Camphor',
  'Carvacrol',
  'Carvone',
  'Caryophyllene',
  'Caryophyllene Oxide',
  'Cedrene',
  'Cedrol',
  'cis-Nerolidol',
  'Citral',
  'Citronellol',
  'Cymene',
  'delta-Cadinene',
  'Delta-3-Carene',
  'Elemol',
  'Eucalyptol',
  'Eugenol',
  'Farnesene',
  'Farnesol',
  'Fenchol',
  'Fenchone',
  'Gamma-Eudesmol',
  'Gamma-Terpinene',
  'Geraniol',
  'Geranyl Acetate',
  'Germacrene D',
  'Guaiol',
  'Humulene',
  'Isobornyl Acetate',
  'Isoborneol',
  'Isopulegol',
  'Limonene',
  'Linalool',
  'Linalool Oxide',
  'Menthol',
  'Menthone',
  'Myrcene',
  'Nerol',
  'Nerolidol',
  'Nootkatone',
  'Ocimene',
  'Octyl Acetate',
  'Perillyl Alcohol',
  'Phytane',
  'Phytol',
  'Piperitone',
  'Pulegone',
  '(R)-Endo-(+)-Fenchyl Alcohol',
  'Sabinene',
  'Sabinene Hydrate',
  'Safranal',
  'Spathulenol',
  'Squalene',
  'T-Cadinol',
  'Terpinen-4-ol',
  'Terpineol',
  'Terpinolene',
  'Terpinyl Acetate',
  'Thujone',
  'Thymol',
  'Trans-Caryophyllene',
  'trans-Nerolidol',
  'trans-Ocimene',
  'Valencene',
  'Verbenone',
  'd-Valerolactam (2-piperidone)',
];
